version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080'
      - '50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local