version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'jenkins_data:/bitnami'
volumes:
  jenkins_data:
    driver: local