version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: proxy
    volumes:
      - 'nginx_proxy:/etc/nginx/conf.d/'
      - 'certificates:/etc/ssl-sonic/'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - bridge

volumes:
  nginx_proxy:
    driver: local
  certificates:
    driver: local

networks:
  bridge:
    external: true